--1. Kreiranje pogleda u kome se za svakog instruktora prikazuje broj polaznika koji imaju čas kod nje(ga). Podatke prikazati u opadajucem redosledu po broju polaznika.
CREATE VIEW INSTRUKTORI_I_BROJ_POLAZNIKA
AS
SELECT DISTINCT INSTRUKTOR.ID_BROJ, INSTRUKTOR.LIME, INSTRUKTOR.SSLOVO, INSTRUKTOR.PREZIME, COUNT(*) AS BROJ_POLAZNIKA
FROM INSTRUKTOR, PREDAJE, POHADJA, POLAZNIK
WHERE INSTRUKTOR.ID_BROJ=PREDAJE.ID_INSTRUKTORA 
      AND POLAZNIK.JMBG=POHADJA.JMBG_POLAZNIKA 
      AND PREDAJE.ID_KURSA=POHADJA.ID_KURSA
GROUP BY INSTRUKTOR.ID_BROJ,INSTRUKTOR.LIME, INSTRUKTOR.SSLOVO, INSTRUKTOR.PREZIME
ORDER BY BROJ_POLAZNIKA DESC;



--2. Kreiranje pogleda u kome se prikazuje spisak kurseva, broj instruktora koji predaju na tom kursu i prosečnu platu instruktora koji taj kurs drže. Podatke prikazati u rastucem redosledu po prosecnoj plati na kursu.
CREATE VIEW PROSECNA_PLATA_PO_KURSU
AS
SELECT KURS.NAZIV,KURS.NIVO,KURS.TRAJANJE, AVG(INSTRUKTOR.PLATA) AS PROSECNA_PLATA, COUNT(*) AS BROJ_INSTRUKTORA
FROM KURS, PREDAJE, INSTRUKTOR
WHERE KURS.ID_BROJ=PREDAJE.ID_KURSA
	  AND PREDAJE.ID_INSTRUKTORA=INSTRUKTOR.ID_BROJ
GROUP BY KURS.NAZIV,KURS.NIVO,KURS.TRAJANJE
ORDER BY PROSECNA_PLATA;
