--1. Kreiranje indeksa nad kolonama IME i PREZIME u tabeli POLAZNIK
CREATE INDEX POLAZNIK_IMEPREZIME_IND
ON POLAZNIK(IME DESC, PREZIME DESC);



--2. Kreiranje indeksa nad kolonom NAZIV i NIVO tabele KURS
CREATE INDEX KURS_NAZIVNIVO_IND
ON KURS(NAZIV ASC, NIVO ASC);
