INSERT INTO INSTRUKTOR (ID_BROJ, LIME, SSLOVO, PREZIME, DAT_RODJ, ST_SPREMA, DAT_DIPL, BROJ_TELEFONA, OPSTINA, ULICA, BROJ, PLATA ) VALUES (11, 'Vladan','K', 'Vladanovic', '21-Oct-70', 'magistar', '23-Dec-95', '064/4535-754','Medijana','Vojvode Gojka', 24, 75000);

INSERT INTO PREDAJE (ID_KURSA, ID_INSTRUKTORA) VALUES (1, 11);
