CREATE TABLE POLAZNIK(
	JMBG NUMBER(13) CONSTRAINT POLAZNIK_PK PRIMARY KEY,
	IME VARCHAR(30) NOT NULL,
	PREZIME VARCHAR(50) NOT NULL,
	E_MAIL VARCHAR(50),
	BROJ_TELEFONA VARCHAR(15),
	OPSTINA VARCHAR(20),
	ULICA VARCHAR(50),
	BROJ NUMBER (4)
);

CREATE TABLE INSTRUKTOR(
	ID_BROJ NUMBER(5) CONSTRAINT INSTRUKTOR_PK PRIMARY KEY,
	LIME VARCHAR(30) NOT NULL,
	SSLOVO CHAR(1) NOT NULL,
	PREZIME VARCHAR(50)NOT NULL,
	DAT_RODJ DATE,
	ST_SPREMA VARCHAR(50),
	DAT_DIPL DATE,
	BROJ_TELEFONA VARCHAR(15),
	OPSTINA VARCHAR(20),
	ULICA VARCHAR(50),
	BROJ NUMBER(4),
	PLATA NUMBER CONSTRAINT INSTRUKTOR_PLATA_CK CHECK (PLATA > 0)
);

CREATE TABLE UCIONICA(
	BROJ NUMBER(4) CONSTRAINT UCIONICA_PK PRIMARY KEY,
	NAZIV VARCHAR(30),
	SPRAT NUMBER(1) NOT NULL,
	KAPACITET NUMBER(3),
	BR_RACUNARA NUMBER(3)
);

CREATE TABLE DODATNA_OPREMA(
	BROJ_UCIONICE NUMBER(4) NOT NULL,
	TIP VARCHAR(50),
	PROIZVODJAC VARCHAR(50),
	MODEL VARCHAR(50),
	DAT_NABAVKE DATE,
	
	CONSTRAINT DODATNA_OPREMA_FK FOREIGN KEY (BROJ_UCIONICE) REFERENCES UCIONICA(BROJ),
	CONSTRAINT DODATNA_OPREMA_PK PRIMARY KEY (TIP , PROIZVODJAC , MODEL , BROJ_UCIONICE)
);

CREATE TABLE KURS(
	ID_BROJ NUMBER(4) CONSTRAINT KURS_PK PRIMARY KEY,
	NAZIV VARCHAR(100) NOT NULL,
	NIVO VARCHAR(15),
	TRAJANJE NUMBER(4),
	CENA NUMBER CONSTRAINT KURS_CENA_CK CHECK (CENA > 0),
	BROJ_UCIONICE NUMBER(4) NOT NULL,
	
	CONSTRAINT KURS_UCIONCA_FK FOREIGN KEY (BROJ_UCIONICE) REFERENCES UCIONICA(BROJ)
);

CREATE TABLE PREDAJE(
	ID_KURSA NUMBER(4) NOT NULL, 
	ID_INSTRUKTORA NUMBER(5) NOT NULL,
	
	CONSTRAINT PREDAJE_PK PRIMARY KEY (ID_KURSA, ID_INSTRUKTORA),
	CONSTRAINT PREDAJE_KURS_FK FOREIGN KEY (ID_KURSA) REFERENCES KURS(ID_BROJ),
	CONSTRAINT PREDAJE_INSTRUKTOR_FK FOREIGN KEY (ID_INSTRUKTORA) REFERENCES INSTRUKTOR(ID_BROJ)
);

CREATE TABLE POHADJA(
	ID_KURSA NUMBER(4),
	JMBG_POLAZNIKA NUMBER(13),
	DAT_UPISA DATE,
	POPUST NUMBER(5, 3),
	
	CONSTRAINT POHADJA_PK PRIMARY KEY (ID_KURSA, JMBG_POLAZNIKA),
	CONSTRAINT POHADJA_KURS_FK FOREIGN KEY (ID_KURSA) REFERENCES KURS(ID_BROJ),
	CONSTRAINT POHADJA_POLAZNIK_FK FOREIGN KEY (JMBG_POLAZNIKA)  REFERENCES POLAZNIK(JMBG)
);

CREATE TABLE E_MAIL_INSTRUKTORA(
	E_MAIL VARCHAR(50),
	ID_INSTRUKTORA NUMBER(5),
	
	CONSTRAINT E_MAIL_INSTRUKTOR_FK FOREIGN KEY (ID_INSTRUKTORA) REFERENCES INSTRUKTOR(ID_BROJ),
	CONSTRAINT E_MAIL_PK PRIMARY KEY (E_MAIL, ID_INSTRUKTORA)
);

