INSERT INTO UCIONICA (BROJ, NAZIV, SPRAT, KAPACITET, BR_RACUNARA) VALUES (301, 'Racunarska 1', 2, 50, 25);
INSERT INTO UCIONICA (BROJ, NAZIV, SPRAT, KAPACITET, BR_RACUNARA) VALUES (102, 'Racunarska 2', 0, 70, 40);
INSERT INTO UCIONICA (BROJ, NAZIV, SPRAT, KAPACITET, BR_RACUNARA) VALUES (201, 'LAN LAB 1', 1, 20, 10);
INSERT INTO UCIONICA (BROJ, NAZIV, SPRAT, KAPACITET, BR_RACUNARA) VALUES (101, 'LAN LAB 2', 0, 25, 25);
INSERT INTO UCIONICA (BROJ, NAZIV, SPRAT, KAPACITET, BR_RACUNARA) VALUES (302, 'WAN LAB', 2, 30, 10);
INSERT INTO UCIONICA (BROJ, NAZIV, SPRAT, KAPACITET, BR_RACUNARA) VALUES (202, 'Wireless tehnologije', 1, 10, 10);
INSERT INTO UCIONICA (BROJ, NAZIV, SPRAT, KAPACITET, BR_RACUNARA) VALUES (303, 'Fun room', 2, 15, 0);
